version: '3.3'

services:

  frontend:
    container_name: frontend
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - CHOKIDAR_USEPOLLING=true
  webserver:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html
