# Generated by Django 4.2 on 2023-05-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_address_user_city_user_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_token',
            new_name='otp_verification',
        ),
    ]
