# Generated by Django 4.2 on 2023-05-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_rename_email_verification_token_user_otp_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_verification',
            new_name='email_verification_token',
        ),
    ]
