# Generated by Django 4.2 on 2023-05-22 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0010_role_permissions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
