# Generated by Django 4.2 on 2023-05-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_remove_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
    ]
