# Generated by Django 4.2 on 2023-06-28 07:47

from django.db import migrations, models

import auth_app.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0013_remove_role_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to=auth_app.models.user.User.upload_to,
            ),
        ),
    ]
