# Generated by Django 4.2 on 2023-04-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprule',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='grouprule',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='./files/product/images/'),
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='transfer',
            name='warehouse',
            field=models.ManyToManyField(to='inventory.warehouse'),
        ),
    ]
