# Generated by Django 4.2 on 2023-04-25 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transferdetail',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 8, 50, 16, 722861, tzinfo=datetime.timezone.utc)),
        ),
    ]
