# Generated by Django 4.2 on 2023-04-25 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferdetail',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 8, 53, 7, 55173, tzinfo=datetime.timezone.utc)),
        ),
    ]
