# Generated by Django 4.2 on 2023-04-25 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_partner_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='contact_phone',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='transferdetail',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 8, 53, 40, 824375, tzinfo=datetime.timezone.utc)),
        ),
    ]
