# Generated by Django 4.2 on 2023-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogisticController',
            new_name='Outcome',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='grouprule',
            options={'verbose_name': 'group of rules', 'verbose_name_plural': 'groups of rules'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationstock',
            options={'verbose_name': 'Location Stock', 'verbose_name_plural': 'Location Stocks'},
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ['created_date'], 'verbose_name': 'Outcome', 'verbose_name_plural': 'Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='outcomedetail',
            options={'verbose_name': 'Outcome detail', 'verbose_name_plural': 'Outcome details'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Rule', 'verbose_name_plural': 'Rules'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'Transfer', 'verbose_name_plural': 'Transfers'},
        ),
        migrations.AlterModelOptions(
            name='transferdetail',
            options={'verbose_name': 'Transfer Detail', 'verbose_name_plural': 'Transfer Details'},
        ),
        migrations.RenameField(
            model_name='outcomedetail',
            old_name='logistics',
            new_name='outcome',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='./inventory/static/inventory/images/products/'),
        ),
        migrations.AlterModelTable(
            name='outcome',
            table='outcome',
        ),
    ]
