# Generated by Django 4.2 on 2023-04-25 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_partner_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='transfer',
        ),
        migrations.AlterField(
            model_name='transferdetail',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 9, 2, 46, 133310, tzinfo=datetime.timezone.utc)),
        ),
    ]
