# Generated by Django 4.2 on 2023-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_rule_group_alter_transfer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='type',
            field=models.CharField(blank=True, choices=[('STRAIGHT', 'Get straight'), ('LOCATION', 'Get from anothere location'), ('WAREHOUSE', 'Get from another warehouse')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
