# Generated by Django 4.2 on 2023-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rule_type_alter_rule_description_alter_rule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(blank=True, choices=[('STRAIGHT', 'If have get straight'), ('LOCATION', "If location A don't have, get from location B"), ('WAREHOUSE', "If all locations of Warehouse A don't have, get from warehouse B")], max_length=255),
        ),
    ]
