# Generated by Django 4.2 on 2023-05-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
    ]
