# Generated by Django 4.2 on 2023-04-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_rule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='type',
        ),
        migrations.AddField(
            model_name='rule',
            name='types_of_rule',
            field=models.CharField(choices=[('RL1', 'If location A of Warehouse A have, get straight'), ('RL2', "If location A don't have, get from location B"), ('RL3', "If warehouse A don't have, get from warehouse B")], default='RL1', max_length=255),
        ),
    ]
