# Generated by Django 4.2 on 2023-04-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_rule_types_of_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='types_of_rule',
            field=models.CharField(choices=[('STRAIGHT', 'If location A of Warehouse A have, get straight'), ('ANT_LC', "If location A don't have, get from location B")], default='STRAIGHT', max_length=255),
        ),
    ]
