# Generated by Django 4.2 on 2023-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_product_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
