# Generated by Django 4.2 on 2023-06-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationstock",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_stocks",
                to="inventory.product",
            ),
        ),
    ]
