# Generated by Django 4.2 on 2023-06-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_locationstock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
