# Generated by Django 4.2 on 2023-06-02 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_remove_locationstock_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationstock",
            name="stock_items",
        ),
    ]
