# Generated by Django 4.2 on 2023-06-02 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_locationstock_product_locationstock_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationstock",
            name="name",
        ),
    ]
