# Generated by Django 4.2 on 2023-06-05 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_remove_locationstock_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locationstock",
            old_name="stock",
            new_name="quantity",
        ),
    ]
