# Generated by Django 4.2 on 2023-06-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_stock_locationstock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rule', to='inventory.product'),
        ),
    ]
