# Generated by Django 4.2 on 2023-06-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_rule_product_product_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstock',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_stocks', to='inventory.rule'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='inventory.grouprule'),
        ),
    ]
