# Generated by Django 4.2 on 2023-06-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_rule_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_location_rule', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='rule',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_location_rule', to='inventory.location'),
        ),
    ]
