# Generated by Django 4.2 on 2023-06-08 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_remove_product_rule_product_group_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetail',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.location'),
        ),
    ]
