# Generated by Django 4.2 on 2023-06-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0030_remove_transferdetail_product_transferdetail_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="warehouse",
        ),
        migrations.AddField(
            model_name="transfer",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="inventory.warehouse",
            ),
        ),
    ]
