# Generated by Django 4.2 on 2023-06-08 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_outcomedetail_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdetail',
            name='destination_location',
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='inventory.location'),
        ),
    ]
