# Generated by Django 4.2 on 2023-06-19 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0035_location_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
