# Generated by Django 4.2 on 2023-06-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0036_partner_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="partner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="inventory.partner",
            ),
        ),
    ]
