# Generated by Django 4.2 on 2023-06-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0037_location_partner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="type",
        ),
        migrations.AddField(
            model_name="transferdetail",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="transferdetail",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("('PENDING', 'On Pending')", "On Pending"),
                    ("('RECEIVED', 'Received')", "Received"),
                    ("('TRANSFER', 'On Transfer')", "On Transfer"),
                    ("COMPLETED", "Completed"),
                ],
                default="('PENDING', 'On Pending')",
                max_length=255,
            ),
        ),
    ]
