# Generated by Django 4.2 on 2023-06-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0038_remove_location_type_transferdetail_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="source_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="inventory.location",
            ),
        ),
    ]
