# Generated by Django 4.2 on 2023-06-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0039_transfer_source_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="inventory.partner",
            ),
        ),
    ]
