# Generated by Django 4.2 on 2023-06-20 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0040_alter_location_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcome",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="inventory.location",
            ),
        ),
    ]
