# Generated by Django 4.2 on 2023-06-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0041_outcome_destination_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outcome",
            name="destination_location",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="warehouse",
        ),
        migrations.AddField(
            model_name="outcome",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="inventory.warehouse",
            ),
        ),
    ]
