# Generated by Django 4.2 on 2023-07-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0044_grouprule_user_rule_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
