# Generated by Django 4.2 on 2023-07-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0045_transfer_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outcome",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "On Pending"),
                    ("RECEIVED", "Received"),
                    ("SHIPPING", "On Shipping"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transferdetail",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "On Pending"),
                    ("RECEIVED", "Received"),
                    ("TRANSFER", "On Transfer"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
