# Generated by Django 4.2 on 2023-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0046_alter_outcome_status_alter_transferdetail_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="is_import",
            field=models.BooleanField(default=False),
        ),
    ]
