# Generated by Django 4.2 on 2023-07-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0048_transferdetail_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="total_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
