# Generated by Django 4.2 on 2023-07-10 02:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
